version: '3.8'

services:
  backend:
    build:
      context: ./task-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build:
      context: ./task-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend